### ISSUE TITLE
X and Z axis looks great, Y is much worse...

### ISSUE THREAD

**Issue by antithing** [ZhenghaoFei/visual_odom#1]
Hi! Thank you for making this code available. I have it running on the KITTI data, and it looks great in rotation, and in translation X and Y (left/right and forward/back). In the Y axis(up/down), it is inverted, (down where it should be up)  and drifts off the ground truth straight away.  Did you see this same behavior? Can you think of anything I can do to improve this result?  

Thanks again.

**Comment by ZhenghaoFei** [comment]
Hi antithing,

It is possible that I got the Z axis(up/down) wrong since I didn't check that direction, I will recheck codes related to this and make the change later. I suppose you have tried inverted Z back and still see the drifts. There is a sanity check during integration which only check X and Y, may be that is related to the Z drift.

Thanks

**Comment by antithing** [comment]
Hi! I have tried inverting the axis but I still see the drift. Thank you very much. Please let me know what you find. The other axes are all very accurate. Impressive work! Thanks again.

**Comment by antithing** [comment]
Hi again, did you have any time to look into this? Thanks!

**Comment by ZhenghaoFei** [comment]
Hi antithing,

I rechecked the whole code and improved some place such as validate the circular matching. The overall accuracy improved in all axis, you can take a look. The previous up/down drift should be caused by a single huge wrong error estimation of pitch angle at the beginning. The current code may still has this problem at some time but it should be less likely to happen than previous code. You can probably make the code more robust by carefully select the features, tune the feature set sets or just add sanity check to pitch angle change.

Best

**Comment by antithing** [comment]
Thank you! it looks much better. :) I am going to look at adding bundle adjustment and global map saving. 

Thanks again!

**Comment by ZhenghaoFei** [comment]
Good Luck!
