### ISSUE TITLE
Results on KITTI 00 dataset

### ISSUE THREAD

**Issue by YilmazKadir** [ZhenghaoFei/visual_odom#8]
Hello,
When I run your code this is the result I get from KITTI dataset sequence 00. 
![kitti_00](https://user-images.githubusercontent.com/59517677/79055914-7ed45680-7c59-11ea-8415-b4af3dda952e.png)

Your results seem to be better. Did you use the same calibration file when you recorded the demo video? Do you guys also get the same result  or am I doing something wrong? 
Note: I am using grayscale dataset

**Comment by ZhenghaoFei** [comment]
Hi kdr,

The calibration didn't change. However, the result in the readme was obtained using the code several versions ago, so it is possible that the result is slightly different from the current version's. The reason for changing was due to some stability concerns and running speed.

You can take a look at the code history or play with the parameters such as bucket size, num of feature per bucket, total feature number, the feature extraction method, etc..  

Good luck!

**Comment by YilmazKadir** [comment]
Hello,
Thank you very much for your quick response. I tried the version at 26 Nov. 2018, and I got the same results.
